spring.application.name=eureka
server.port=8761

# El servidor no se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
